# Generated by Django 5.2 on 2025-05-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='create_at',
        ),
        migrations.AddField(
            model_name='announcement',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
